name: 02-workflow-events

on: 
  pull_request:
  workflow_dispatch:

jobs: 
  workflow-test:
    runs-on: ubuntu-latest
    steps:
      - name: show the trigger
        run: echo "i have triggered by a ${{ github.event_name}} events."