name: 04-react-app

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-react-app/react-app
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: install dependencies
        run: npm ci
      - name: Run Unit test
        run: npm run test