name: 05-1-filters activity

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Run whenever a PR is opened or synchronized AND base branch is main"