name: 11-working-with-input

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: skip the deployment and only print build output
        default: false
      target:
        type: environment
        required: true
        description: which environment the workflow will target
      tag:
        type: choice
        options:
          - V1
          - V2
          - V3
        default: v3
        description: Release from which to build and deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building tag ${{ inputs.tag  }}"
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-run }}
    environment: ${{ inputs.target }}
    steps:
      - name: Deploy
        run: echo "Deploying tag ${{ inputs.target  }}"
