name: 13-caching

on: 
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute cache step
        type: boolean
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: install dependencies
        run: npm ci
      - name: Run Unit test
        run: npm run test
      - name: Building
        run: npm run build
      - name: Deploy to nonprod
        run: echo "Deploying to nonprod"
      
      