name: 16-environment
run-name: 16-environment | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging

jobs:
  echo:
    runs-on:
    environment:
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value'}}
    steps:
      - name: Echo vars
        run: |
          echo "Env variable: ${{ env.my-env-value }}"
          