name: 17-1-custom-action
run-name: 17-1-custom-action -composite | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: which environment to target
        type: choice
        options:
          - dev
          - prod

env:
  working-directory: 17-customa-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node and NPM dependencies
        uses: .github/actions/composite-cache-deps
        with:
          node-version: 20.x
          working-dir: ${{ env.working-directory }}
          target-env: ${{ inputs.target-env }}
      - name: test
        run: npm run test
      - name: build
        run: npm run build
